<Project>
  <PropertyGroup Condition="'$(MSBuildProjectExtension)' == '.csproj'">
    <BaseOutputPath>$(MSBuildProjectDirectory)\Build\bin\</BaseOutputPath>
    <BaseIntermediateOutputPath>$(MSBuildProjectDirectory)\Build\obj\$(Platform)\</BaseIntermediateOutputPath>
    <MSBuildProjectExtensionsPath>$(BaseIntermediateOutputPath)</MSBuildProjectExtensionsPath>
    <DefaultItemExcludes>$(DefaultItemExcludes);bin\**;obj\**;Build\**</DefaultItemExcludes>
  </PropertyGroup>
</Project>
